server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wonderful?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&useSSL=false
    username: root
    password: '#*hui666#*hui'
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wonderful.bean.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
